### ISSUE TITLE
Add package file

### ISSUE THREAD

**Issue by MasterQ32** [ziglibs/ansi-term#11]
Add a single file that can be added as a package so people can easily use this library

**Comment by joachimschmidt557** [comment]
Yes, I will do that. But before that, I'm thinking of renaming this library from `zig-ansi-term` to just `ansi-term`.

**Comment by joachimschmidt557** [comment]
Implemented in https://github.com/ziglibs/ansi-term/commit/8db2180d04d5c25155a1ad9ebd6a7a3c8d57dc59
